#!/bin/bash

function xalbum {
	while true; do
		album=$(mpc --format "[%album%]" | head -n 1 | tail -1)
		echo -e "$album"
		sleep 1
	done
}

function xartist {
	while true; do
		artist=$(mpc --format "[%artist%]" | head -n 1 | tail -1)
		echo -e "$artist"
		sleep 1
	done
}

function xtitle {
	while true; do
		title=$(mpc --format "[%title%]" | head -n 1 | tail -1)
		echo -e "$title"
		sleep 1
	done
}

xalbum | /bin/lemonbar -g "160x12+1760+192" -d -B '#424242' -F '#f6dedc' -f '-wiktorb-leggie-medium-*-*-*-12-*-*-*-*-*-*-*'&
xartist | /bin/lemonbar -g "160x12+1760+180" -d -B '#424242' -F '#f6dedc' -f '-wiktorb-leggie-medium-*-*-*-12-*-*-*-*-*-*-*' &
xtitle | /bin/lemonbar -g "160x12+1760+204" -d -B '#424242' -F '#f6dedc' -f '-wiktorb-leggie-medium-*-*-*-12-*-*-*-*-*-*-*' &
